name: tests

# Run tests on pushes to main and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Security: restrict permissions for CI jobs
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      # Extract Python version from hatch matrix configuration
      - name: Get Python version from pyproject.toml
        id: python-version
        run: |
          python_version=$(python -c "import tomllib; f=open('pyproject.toml','rb'); data=tomllib.load(f); print(data['tool']['hatch']['envs']['all']['matrix']['python'][0])")
          echo "version=$python_version" >> $GITHUB_OUTPUT
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.python-version.outputs.version }}
          cache: 'pip'
      
      # Install hatch for environment management
      - name: Install hatch
        run: pip install hatch
      
      # Run code quality checks using hatch
      - name: Run linting and formatting checks
        run: hatch run lint:check
      
      # Run tests using hatch
      - name: Run tests
        run: hatch run test